export const tagOptions = [
    {
      key: "Undo",
      text: "Undo",
      value: "",
    },
    {
      key: "Adventure stories",
      text: "Adventure stories",
      value: "Adventure stories",
      // label: { color: "red", empty: true, circular: true },
    },
    {
      key: "Classics",
      text: "Classics",
      value: "Classics",
      // label: { color: "blue", empty: true, circular: true },
    },
    {
      key: "Crime",
      text: "Crime",
      value: "Crime",
      // label: { color: "black", empty: true, circular: true },
    },
    {
      key: "Fairy tales",
      text: "Fairy tales",
      value: "Fairy tales",
      // label: { color: "purple", empty: true, circular: true },
    },
    {
      key: "Fantasy",
      text: "Fantasy",
      value: "Fantasy",
      // label: { color: "orange", empty: true, circular: true },
    },
    {
      key: "Historical fiction",
      text: "Historical fiction",
      value: "Historical fiction",
      // label: { empty: true, circular: true },
    },
    {
      key: "Horror",
      text: "Horror",
      value: "Horror",
      // label: { color: "yellow", empty: true, circular: true },
    },
    {
      key: "Literary",
      text: "Literary",
      value: "Literar",
      // label: { color: "pink", empty: true, circular: true },
    },
    {
      key: "Mystery",
      text: "Mystery",
      value: "Mystery",
      // label: { color: "green", empty: true, circular: true },
    },
    {
      key: "Poetry",
      text: "Poetry",
      value: "Poetry",
      // label: { color: "green", empty: true, circular: true },
    },
    {
      key: "Romance",
      text: "Romance",
      value: "Romance",
      // label: { color: "green", empty: true, circular: true },
    },
    {
      key: "Science fiction",
      text: "Science fiction",
      value: "Science fiction",
      // label: { color: "green", empty: true, circular: true },
    },
    {
      key: "Thrillers",
      text: "Thrillers",
      value: "Thrillers",
      // label: { color: "green", empty: true, circular: true },
    },
    {
      key: "Biography",
      text: "Biography",
      value: "Biography",
      // label: { color: "green", empty: true, circular: true },
    },
    {
      key: "Women's fiction",
      text: "Women's fiction",
      value: "Women's fiction",
      // label: { color: "green", empty: true, circular: true },
    },
    {
      key: "Self-Help",
      text: "Self-Help",
      value: "Self-Help",
      // label: { color: "green", empty: true, circular: true },
    },
  ];